//
//  MaterialDesignIcon5
//
//  Created by tichise on 2015/5/7 15/05/07.
//  Copyright (c) 2015 tichise. All rights reserved.
//

import UIKit

/**
 * マテリアルデザインアイコンのコードを返すクラス
 */
extension MaterialDesignIcon {
    @objc public static let voiceChat24px = "\u{ec3c}"
    @objc public static let voiceChat48px = "\u{ec3d}"
    @objc public static let vpnLock24px = "\u{ec3e}"
    @objc public static let vpnLock48px = "\u{ec3f}"
    @objc public static let cake18px = "\u{ec40}"
    @objc public static let cake24px = "\u{ec41}"
    @objc public static let cake48px = "\u{ec42}"
    @objc public static let domain18px = "\u{ec43}"
    @objc public static let domain24px = "\u{ec44}"
    @objc public static let domain48px = "\u{ec45}"
    @objc public static let group18px = "\u{ec46}"
    @objc public static let group24px = "\u{ec47}"
    @objc public static let group48px = "\u{ec48}"
    @objc public static let groupAdd18px = "\u{ec49}"
    @objc public static let groupAdd24px = "\u{ec4a}"
    @objc public static let groupAdd48px = "\u{ec4b}"
    @objc public static let locationCity18px = "\u{ec4c}"
    @objc public static let locationCity24px = "\u{ec4d}"
    @objc public static let locationCity48px = "\u{ec4e}"
    @objc public static let mood18px = "\u{ec4f}"
    @objc public static let mood24px = "\u{ec50}"
    @objc public static let mood48px = "\u{ec51}"
    @objc public static let notifications24px = "\u{ec52}"
    @objc public static let notifications48px = "\u{ec53}"
    @objc public static let notificationsNone24px = "\u{ec54}"
    @objc public static let notificationsNone48px = "\u{ec55}"
    @objc public static let notificationsOff24px = "\u{ec56}"
    @objc public static let notificationsOff48px = "\u{ec57}"
    @objc public static let notificationsOn24px = "\u{ec58}"
    @objc public static let notificationsOn48px = "\u{ec59}"
    @objc public static let notificationsPaused24px = "\u{ec5a}"
    @objc public static let notificationsPaused48px = "\u{ec5b}"
    @objc public static let pages18px = "\u{ec5c}"
    @objc public static let pages24px = "\u{ec5d}"
    @objc public static let pages48px = "\u{ec5e}"
    @objc public static let partyMode24px = "\u{ec5f}"
    @objc public static let partyMode48px = "\u{ec60}"
    @objc public static let people18px = "\u{ec61}"
    @objc public static let people24px = "\u{ec62}"
    @objc public static let people48px = "\u{ec63}"
    @objc public static let peopleOutline24px = "\u{ec64}"
    @objc public static let peopleOutline48px = "\u{ec65}"
    @objc public static let person18px = "\u{ec66}"
    @objc public static let person24px = "\u{ec67}"
    @objc public static let person48px = "\u{ec68}"
    @objc public static let personAdd18px = "\u{ec69}"
    @objc public static let personAdd24px = "\u{ec6a}"
    @objc public static let personAdd48px = "\u{ec6b}"
    @objc public static let personOutline18px = "\u{ec6c}"
    @objc public static let personOutline24px = "\u{ec6d}"
    @objc public static let personOutline48px = "\u{ec6e}"
    @objc public static let plusOne24px = "\u{ec6f}"
    @objc public static let plusOne48px = "\u{ec70}"
    @objc public static let poll18px = "\u{ec71}"
    @objc public static let poll24px = "\u{ec72}"
    @objc public static let poll48px = "\u{ec73}"
    @objc public static let public24px = "\u{ec74}"
    @objc public static let public48px = "\u{ec75}"
    @objc public static let school24px = "\u{ec76}"
    @objc public static let school48px = "\u{ec77}"
    @objc public static let share24px = "\u{ec78}"
    @objc public static let share48px = "\u{ec79}"
    @objc public static let whatshot18px = "\u{ec7a}"
    @objc public static let whatshot24px = "\u{ec7b}"
    @objc public static let whatshot48px = "\u{ec7c}"
}
