//
//  MaterialDesignIcon5
//
//  Created by tichise on 2015/5/7 15/05/07.
//  Copyright (c) 2015 tichise. All rights reserved.
//

import UIKit

/**
 * マテリアルデザインアイコンのコードを返すクラス
 */
extension MaterialDesignIcon {
    public static let voiceChat24px = "\u{ec3c}"
    public static let voiceChat48px = "\u{ec3d}"
    public static let vpnLock24px = "\u{ec3e}"
    public static let vpnLock48px = "\u{ec3f}"
    public static let cake18px = "\u{ec40}"
    public static let cake24px = "\u{ec41}"
    public static let cake48px = "\u{ec42}"
    public static let domain18px = "\u{ec43}"
    public static let domain24px = "\u{ec44}"
    public static let domain48px = "\u{ec45}"
    public static let group18px = "\u{ec46}"
    public static let group24px = "\u{ec47}"
    public static let group48px = "\u{ec48}"
    public static let groupAdd18px = "\u{ec49}"
    public static let groupAdd24px = "\u{ec4a}"
    public static let groupAdd48px = "\u{ec4b}"
    public static let locationCity18px = "\u{ec4c}"
    public static let locationCity24px = "\u{ec4d}"
    public static let locationCity48px = "\u{ec4e}"
    public static let mood18px = "\u{ec4f}"
    public static let mood24px = "\u{ec50}"
    public static let mood48px = "\u{ec51}"
    public static let notifications24px = "\u{ec52}"
    public static let notifications48px = "\u{ec53}"
    public static let notificationsNone24px = "\u{ec54}"
    public static let notificationsNone48px = "\u{ec55}"
    public static let notificationsOff24px = "\u{ec56}"
    public static let notificationsOff48px = "\u{ec57}"
    public static let notificationsOn24px = "\u{ec58}"
    public static let notificationsOn48px = "\u{ec59}"
    public static let notificationsPaused24px = "\u{ec5a}"
    public static let notificationsPaused48px = "\u{ec5b}"
    public static let pages18px = "\u{ec5c}"
    public static let pages24px = "\u{ec5d}"
    public static let pages48px = "\u{ec5e}"
    public static let partyMode24px = "\u{ec5f}"
    public static let partyMode48px = "\u{ec60}"
    public static let people18px = "\u{ec61}"
    public static let people24px = "\u{ec62}"
    public static let people48px = "\u{ec63}"
    public static let peopleOutline24px = "\u{ec64}"
    public static let peopleOutline48px = "\u{ec65}"
    public static let person18px = "\u{ec66}"
    public static let person24px = "\u{ec67}"
    public static let person48px = "\u{ec68}"
    public static let personAdd18px = "\u{ec69}"
    public static let personAdd24px = "\u{ec6a}"
    public static let personAdd48px = "\u{ec6b}"
    public static let personOutline18px = "\u{ec6c}"
    public static let personOutline24px = "\u{ec6d}"
    public static let personOutline48px = "\u{ec6e}"
    public static let plusOne24px = "\u{ec6f}"
    public static let plusOne48px = "\u{ec70}"
    public static let poll18px = "\u{ec71}"
    public static let poll24px = "\u{ec72}"
    public static let poll48px = "\u{ec73}"
    public static let public24px = "\u{ec74}"
    public static let public48px = "\u{ec75}"
    public static let school24px = "\u{ec76}"
    public static let school48px = "\u{ec77}"
    public static let share24px = "\u{ec78}"
    public static let share48px = "\u{ec79}"
    public static let whatshot18px = "\u{ec7a}"
    public static let whatshot24px = "\u{ec7b}"
    public static let whatshot48px = "\u{ec7c}"
}
